# Generated by Django 5.0.2 on 2025-04-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatroom',
            name='unique_direct_chat_type',
        ),
    ]
