# Generated by Django 5.0.2 on 2025-04-08 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_membership_last_role_change_alter_message_attachment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
